Vegetable.create(name: "broccoli", start_day: 135, end_day: 288)
Vegetable.create(name: "cauliflower", start_day: 166, end_day: 319)
Vegetable.create(name: "corn", start_day: 196, end_day: 319)
Vegetable.create(name: "cucumber", start_day: 181, end_day: 319)
Vegetable.create(name: "eggplant", start_day: 121, end_day: 319)
Vegetable.create(name: "kale", start_day: 166, end_day: 486, winter_vegetable: true)
Vegetable.create(name: "leek", start_day: 227, end_day: 471, winter_vegetable: true)
Vegetable.create(name: "lettuce", start_day: 106, end_day: 350)
Vegetable.create(name: "pepper", start_day: 135, end_day: 319)
Vegetable.create(name: "potato", start_day: 212, end_day: 319)
Vegetable.create(name: "spinach", start_day: 135, end_day: 350)
Vegetable.create(name: "brussels sprouts", start_day: 274, end_day: 470)
Vegetable.create(name: "carrot", start_day: 182, end_day: 360)
Vegetable.create(name: "onion", start_day: 121, end_day: 320)
Vegetable.create(name: "tomato", start_day: 135, end_day: 305)
